name: Deploy Preview

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Setup Expo
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
    
    - name: Install dependencies
      run: npm ci
    
    - name: Create preview
      run: npx eas update --branch preview-${{ github.event.number }} --message "PR Preview for #${{ github.event.number }}"
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
    
    - name: Comment PR with preview link
      uses: actions/github-script@v7
      with:
        script: |
          const body = `📱 **Preview Build Ready!**
          
          Your preview has been deployed and is ready for testing.
          
          Branch: \`preview-${{ github.event.number }}\`
          
          To test on Expo Go:
          1. Download Expo Go on your device
          2. Open the app and scan the QR code from the EAS dashboard
          3. Your preview will load automatically
          
          [View on EAS Dashboard](https://expo.dev/accounts/your-account/projects/storagespace/updates)`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });