name: Security Audit

on:
  push:
    branches: [ main, development, staging ]
  pull_request:
    branches: [ main, development, staging ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run npm audit
      run: npm audit --audit-level=moderate
    
    - name: Run npm audit fix (dry run)
      run: npm audit fix --dry-run --audit-level=moderate
      continue-on-error: true
    
    - name: Check for security vulnerabilities with Snyk
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    
    - name: Upload npm audit results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: npm-audit-results
        path: npm-audit.json
        retention-days: 90

  secrets-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: TruffleHog OSS
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        head: HEAD
        extra_args: --debug --only-verified